db_connection:
  connection_string: "grpcs://localhost:2135/domain/database"
  insecure: true
  discovery: false
  enable_sdk_metrics: false

client_connection:
  insecure: true
  discovery: false
  allowed_endpoint_domains:
    - .allowed-domain.com
    - allowed-hostname.domain.com
  allow_insecure_endpoint: false

s3:
  endpoint: s3.endpoint.com
  region: s3-region
  bucket: s3-bucket
  path_prefix: cluster-domain
  access_key_id_path: path-to-s3-key
  secret_access_key_path: path-to-s3-sec

auth:
  plugin_path: path/to/plugin.so
  configuration:
    param: value

grpc_server:
  bind_port: 50051
  tls_certificate_path: path/to/tls.crt
  tls_key_path: path/to/tls.key

metrics_server:
  bind_port: 9090
  bind_address: 127.0.0.1
  #tls_certificate_path: path/to/tls.crt
  #tls_key_path: path/to/tls.key

operation_processor:
  operation_ttl_seconds: 86400 # 24 hours
