// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: describe.proto

package ydb_nebius_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TStatusIds_EStatusCode int32

const (
	TStatusIds_UNKNOWN               TStatusIds_EStatusCode = 0
	TStatusIds_SUCCESS               TStatusIds_EStatusCode = 1
	TStatusIds_TRANSIENT             TStatusIds_EStatusCode = 2
	TStatusIds_ERROR                 TStatusIds_EStatusCode = 128
	TStatusIds_INPROGRESS            TStatusIds_EStatusCode = 129
	TStatusIds_TIMEOUT               TStatusIds_EStatusCode = 130
	TStatusIds_NOTREADY              TStatusIds_EStatusCode = 131
	TStatusIds_INTERNAL_ERROR        TStatusIds_EStatusCode = 133
	TStatusIds_REJECTED              TStatusIds_EStatusCode = 134
	TStatusIds_NOTSUPPORTED          TStatusIds_EStatusCode = 135
	TStatusIds_OVERLOADED            TStatusIds_EStatusCode = 136
	TStatusIds_PATH_NOT_EXIST        TStatusIds_EStatusCode = 137
	TStatusIds_ACCESS_DENIED         TStatusIds_EStatusCode = 138
	TStatusIds_BAD_REQUEST           TStatusIds_EStatusCode = 150
	TStatusIds_QUERY_ERROR           TStatusIds_EStatusCode = 151
	TStatusIds_PROCESS_ERROR         TStatusIds_EStatusCode = 152
	TStatusIds_BAD_SESSION           TStatusIds_EStatusCode = 153
	TStatusIds_LOCKS_INVALIDATED     TStatusIds_EStatusCode = 170
	TStatusIds_LOCKS_ACQUIRE_FAILURE TStatusIds_EStatusCode = 171
	TStatusIds_SCHEME_ERROR          TStatusIds_EStatusCode = 172
)

// Enum value maps for TStatusIds_EStatusCode.
var (
	TStatusIds_EStatusCode_name = map[int32]string{
		0:   "UNKNOWN",
		1:   "SUCCESS",
		2:   "TRANSIENT",
		128: "ERROR",
		129: "INPROGRESS",
		130: "TIMEOUT",
		131: "NOTREADY",
		133: "INTERNAL_ERROR",
		134: "REJECTED",
		135: "NOTSUPPORTED",
		136: "OVERLOADED",
		137: "PATH_NOT_EXIST",
		138: "ACCESS_DENIED",
		150: "BAD_REQUEST",
		151: "QUERY_ERROR",
		152: "PROCESS_ERROR",
		153: "BAD_SESSION",
		170: "LOCKS_INVALIDATED",
		171: "LOCKS_ACQUIRE_FAILURE",
		172: "SCHEME_ERROR",
	}
	TStatusIds_EStatusCode_value = map[string]int32{
		"UNKNOWN":               0,
		"SUCCESS":               1,
		"TRANSIENT":             2,
		"ERROR":                 128,
		"INPROGRESS":            129,
		"TIMEOUT":               130,
		"NOTREADY":              131,
		"INTERNAL_ERROR":        133,
		"REJECTED":              134,
		"NOTSUPPORTED":          135,
		"OVERLOADED":            136,
		"PATH_NOT_EXIST":        137,
		"ACCESS_DENIED":         138,
		"BAD_REQUEST":           150,
		"QUERY_ERROR":           151,
		"PROCESS_ERROR":         152,
		"BAD_SESSION":           153,
		"LOCKS_INVALIDATED":     170,
		"LOCKS_ACQUIRE_FAILURE": 171,
		"SCHEME_ERROR":          172,
	}
)

func (x TStatusIds_EStatusCode) Enum() *TStatusIds_EStatusCode {
	p := new(TStatusIds_EStatusCode)
	*p = x
	return p
}

func (x TStatusIds_EStatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TStatusIds_EStatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_describe_proto_enumTypes[0].Descriptor()
}

func (TStatusIds_EStatusCode) Type() protoreflect.EnumType {
	return &file_describe_proto_enumTypes[0]
}

func (x TStatusIds_EStatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TStatusIds_EStatusCode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TStatusIds_EStatusCode(num)
	return nil
}

// Deprecated: Use TStatusIds_EStatusCode.Descriptor instead.
func (TStatusIds_EStatusCode) EnumDescriptor() ([]byte, []int) {
	return file_describe_proto_rawDescGZIP(), []int{0, 0}
}

// Minimal status codes extracted from NKikimrIssues.TStatusIds.EStatusCode
type TStatusIds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TStatusIds) Reset() {
	*x = TStatusIds{}
	mi := &file_describe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TStatusIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TStatusIds) ProtoMessage() {}

func (x *TStatusIds) ProtoReflect() protoreflect.Message {
	mi := &file_describe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TStatusIds.ProtoReflect.Descriptor instead.
func (*TStatusIds) Descriptor() ([]byte, []int) {
	return file_describe_proto_rawDescGZIP(), []int{0}
}

// Extracted from NKikimrSchemeOp.TUserAttribute
type TUserAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *string                `protobuf:"bytes,1,opt,name=Key" json:"Key,omitempty"`
	Value         *string                `protobuf:"bytes,2,opt,name=Value" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TUserAttribute) Reset() {
	*x = TUserAttribute{}
	mi := &file_describe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TUserAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TUserAttribute) ProtoMessage() {}

func (x *TUserAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_describe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TUserAttribute.ProtoReflect.Descriptor instead.
func (*TUserAttribute) Descriptor() ([]byte, []int) {
	return file_describe_proto_rawDescGZIP(), []int{1}
}

func (x *TUserAttribute) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *TUserAttribute) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

// Extracted from NKikimrSchemeOp.TDescribeOptions
type TDescribeOptions struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	ReturnPartitioningInfo     *bool                  `protobuf:"varint,1,opt,name=ReturnPartitioningInfo,def=1" json:"ReturnPartitioningInfo,omitempty"`
	ReturnPartitionConfig      *bool                  `protobuf:"varint,2,opt,name=ReturnPartitionConfig,def=1" json:"ReturnPartitionConfig,omitempty"`
	BackupInfo                 *bool                  `protobuf:"varint,3,opt,name=BackupInfo,def=0" json:"BackupInfo,omitempty"`
	ReturnPartitionStats       *bool                  `protobuf:"varint,4,opt,name=ReturnPartitionStats,def=0" json:"ReturnPartitionStats,omitempty"`
	ReturnChildren             *bool                  `protobuf:"varint,5,opt,name=ReturnChildren,def=1" json:"ReturnChildren,omitempty"`
	ReturnBoundaries           *bool                  `protobuf:"varint,6,opt,name=ReturnBoundaries,def=0" json:"ReturnBoundaries,omitempty"`
	ShowPrivateTable           *bool                  `protobuf:"varint,7,opt,name=ShowPrivateTable,def=0" json:"ShowPrivateTable,omitempty"`
	ReturnChannelsBinding      *bool                  `protobuf:"varint,8,opt,name=ReturnChannelsBinding,def=0" json:"ReturnChannelsBinding,omitempty"`
	ReturnRangeKey             *bool                  `protobuf:"varint,9,opt,name=ReturnRangeKey,def=1" json:"ReturnRangeKey,omitempty"`
	ReturnSetVal               *bool                  `protobuf:"varint,10,opt,name=ReturnSetVal,def=0" json:"ReturnSetVal,omitempty"`
	ReturnIndexTableBoundaries *bool                  `protobuf:"varint,11,opt,name=ReturnIndexTableBoundaries,def=0" json:"ReturnIndexTableBoundaries,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

// Default values for TDescribeOptions fields.
const (
	Default_TDescribeOptions_ReturnPartitioningInfo     = bool(true)
	Default_TDescribeOptions_ReturnPartitionConfig      = bool(true)
	Default_TDescribeOptions_BackupInfo                 = bool(false)
	Default_TDescribeOptions_ReturnPartitionStats       = bool(false)
	Default_TDescribeOptions_ReturnChildren             = bool(true)
	Default_TDescribeOptions_ReturnBoundaries           = bool(false)
	Default_TDescribeOptions_ShowPrivateTable           = bool(false)
	Default_TDescribeOptions_ReturnChannelsBinding      = bool(false)
	Default_TDescribeOptions_ReturnRangeKey             = bool(true)
	Default_TDescribeOptions_ReturnSetVal               = bool(false)
	Default_TDescribeOptions_ReturnIndexTableBoundaries = bool(false)
)

func (x *TDescribeOptions) Reset() {
	*x = TDescribeOptions{}
	mi := &file_describe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TDescribeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TDescribeOptions) ProtoMessage() {}

func (x *TDescribeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_describe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TDescribeOptions.ProtoReflect.Descriptor instead.
func (*TDescribeOptions) Descriptor() ([]byte, []int) {
	return file_describe_proto_rawDescGZIP(), []int{2}
}

func (x *TDescribeOptions) GetReturnPartitioningInfo() bool {
	if x != nil && x.ReturnPartitioningInfo != nil {
		return *x.ReturnPartitioningInfo
	}
	return Default_TDescribeOptions_ReturnPartitioningInfo
}

func (x *TDescribeOptions) GetReturnPartitionConfig() bool {
	if x != nil && x.ReturnPartitionConfig != nil {
		return *x.ReturnPartitionConfig
	}
	return Default_TDescribeOptions_ReturnPartitionConfig
}

func (x *TDescribeOptions) GetBackupInfo() bool {
	if x != nil && x.BackupInfo != nil {
		return *x.BackupInfo
	}
	return Default_TDescribeOptions_BackupInfo
}

func (x *TDescribeOptions) GetReturnPartitionStats() bool {
	if x != nil && x.ReturnPartitionStats != nil {
		return *x.ReturnPartitionStats
	}
	return Default_TDescribeOptions_ReturnPartitionStats
}

func (x *TDescribeOptions) GetReturnChildren() bool {
	if x != nil && x.ReturnChildren != nil {
		return *x.ReturnChildren
	}
	return Default_TDescribeOptions_ReturnChildren
}

func (x *TDescribeOptions) GetReturnBoundaries() bool {
	if x != nil && x.ReturnBoundaries != nil {
		return *x.ReturnBoundaries
	}
	return Default_TDescribeOptions_ReturnBoundaries
}

func (x *TDescribeOptions) GetShowPrivateTable() bool {
	if x != nil && x.ShowPrivateTable != nil {
		return *x.ShowPrivateTable
	}
	return Default_TDescribeOptions_ShowPrivateTable
}

func (x *TDescribeOptions) GetReturnChannelsBinding() bool {
	if x != nil && x.ReturnChannelsBinding != nil {
		return *x.ReturnChannelsBinding
	}
	return Default_TDescribeOptions_ReturnChannelsBinding
}

func (x *TDescribeOptions) GetReturnRangeKey() bool {
	if x != nil && x.ReturnRangeKey != nil {
		return *x.ReturnRangeKey
	}
	return Default_TDescribeOptions_ReturnRangeKey
}

func (x *TDescribeOptions) GetReturnSetVal() bool {
	if x != nil && x.ReturnSetVal != nil {
		return *x.ReturnSetVal
	}
	return Default_TDescribeOptions_ReturnSetVal
}

func (x *TDescribeOptions) GetReturnIndexTableBoundaries() bool {
	if x != nil && x.ReturnIndexTableBoundaries != nil {
		return *x.ReturnIndexTableBoundaries
	}
	return Default_TDescribeOptions_ReturnIndexTableBoundaries
}

// Extracted from NKikimrSchemeOp.TPathDescription.
// Only UserAttributes are preserved.
type TPathDescription struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserAttributes []*TUserAttribute      `protobuf:"bytes,16,rep,name=UserAttributes" json:"UserAttributes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TPathDescription) Reset() {
	*x = TPathDescription{}
	mi := &file_describe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TPathDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TPathDescription) ProtoMessage() {}

func (x *TPathDescription) ProtoReflect() protoreflect.Message {
	mi := &file_describe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TPathDescription.ProtoReflect.Descriptor instead.
func (*TPathDescription) Descriptor() ([]byte, []int) {
	return file_describe_proto_rawDescGZIP(), []int{3}
}

func (x *TPathDescription) GetUserAttributes() []*TUserAttribute {
	if x != nil {
		return x.UserAttributes
	}
	return nil
}

// Extracted from NKikimrClient.TSchemeDescribe.
type TSchemeDescribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *string                `protobuf:"bytes,1,opt,name=Path" json:"Path,omitempty"`
	PathId        *uint64                `protobuf:"varint,2,opt,name=PathId" json:"PathId,omitempty"`
	SchemeshardId *uint64                `protobuf:"varint,3,opt,name=SchemeshardId" json:"SchemeshardId,omitempty"`
	SecurityToken *string                `protobuf:"bytes,5,opt,name=SecurityToken" json:"SecurityToken,omitempty"`
	Options       *TDescribeOptions      `protobuf:"bytes,6,opt,name=Options" json:"Options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TSchemeDescribe) Reset() {
	*x = TSchemeDescribe{}
	mi := &file_describe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TSchemeDescribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TSchemeDescribe) ProtoMessage() {}

func (x *TSchemeDescribe) ProtoReflect() protoreflect.Message {
	mi := &file_describe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TSchemeDescribe.ProtoReflect.Descriptor instead.
func (*TSchemeDescribe) Descriptor() ([]byte, []int) {
	return file_describe_proto_rawDescGZIP(), []int{4}
}

func (x *TSchemeDescribe) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

func (x *TSchemeDescribe) GetPathId() uint64 {
	if x != nil && x.PathId != nil {
		return *x.PathId
	}
	return 0
}

func (x *TSchemeDescribe) GetSchemeshardId() uint64 {
	if x != nil && x.SchemeshardId != nil {
		return *x.SchemeshardId
	}
	return 0
}

func (x *TSchemeDescribe) GetSecurityToken() string {
	if x != nil && x.SecurityToken != nil {
		return *x.SecurityToken
	}
	return ""
}

func (x *TSchemeDescribe) GetOptions() *TDescribeOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// Extracted from NKikimrClient.TFlatDescribeResponse.
type TFlatDescribeResponse struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Status          *uint32                 `protobuf:"varint,1,opt,name=Status" json:"Status,omitempty"`
	PathDescription *TPathDescription       `protobuf:"bytes,2,opt,name=PathDescription" json:"PathDescription,omitempty"`
	ErrorReason     *string                 `protobuf:"bytes,3,opt,name=ErrorReason" json:"ErrorReason,omitempty"`
	SchemeStatus    *int32                  `protobuf:"varint,4,opt,name=SchemeStatus" json:"SchemeStatus,omitempty"`
	StatusCode      *TStatusIds_EStatusCode `protobuf:"varint,7,opt,name=StatusCode,enum=NKikimrClient.TStatusIds_EStatusCode" json:"StatusCode,omitempty"`
	Path            *string                 `protobuf:"bytes,9,opt,name=Path" json:"Path,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TFlatDescribeResponse) Reset() {
	*x = TFlatDescribeResponse{}
	mi := &file_describe_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TFlatDescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TFlatDescribeResponse) ProtoMessage() {}

func (x *TFlatDescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_describe_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TFlatDescribeResponse.ProtoReflect.Descriptor instead.
func (*TFlatDescribeResponse) Descriptor() ([]byte, []int) {
	return file_describe_proto_rawDescGZIP(), []int{5}
}

func (x *TFlatDescribeResponse) GetStatus() uint32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *TFlatDescribeResponse) GetPathDescription() *TPathDescription {
	if x != nil {
		return x.PathDescription
	}
	return nil
}

func (x *TFlatDescribeResponse) GetErrorReason() string {
	if x != nil && x.ErrorReason != nil {
		return *x.ErrorReason
	}
	return ""
}

func (x *TFlatDescribeResponse) GetSchemeStatus() int32 {
	if x != nil && x.SchemeStatus != nil {
		return *x.SchemeStatus
	}
	return 0
}

func (x *TFlatDescribeResponse) GetStatusCode() TStatusIds_EStatusCode {
	if x != nil && x.StatusCode != nil {
		return *x.StatusCode
	}
	return TStatusIds_UNKNOWN
}

func (x *TFlatDescribeResponse) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

var File_describe_proto protoreflect.FileDescriptor

const file_describe_proto_rawDesc = "" +
	"\n" +
	"\x0edescribe.proto\x12\rNKikimrClient\"\x81\x03\n" +
	"\n" +
	"TStatusIds\"\xf2\x02\n" +
	"\vEStatusCode\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\r\n" +
	"\tTRANSIENT\x10\x02\x12\n" +
	"\n" +
	"\x05ERROR\x10\x80\x01\x12\x0f\n" +
	"\n" +
	"INPROGRESS\x10\x81\x01\x12\f\n" +
	"\aTIMEOUT\x10\x82\x01\x12\r\n" +
	"\bNOTREADY\x10\x83\x01\x12\x13\n" +
	"\x0eINTERNAL_ERROR\x10\x85\x01\x12\r\n" +
	"\bREJECTED\x10\x86\x01\x12\x11\n" +
	"\fNOTSUPPORTED\x10\x87\x01\x12\x0f\n" +
	"\n" +
	"OVERLOADED\x10\x88\x01\x12\x13\n" +
	"\x0ePATH_NOT_EXIST\x10\x89\x01\x12\x12\n" +
	"\rACCESS_DENIED\x10\x8a\x01\x12\x10\n" +
	"\vBAD_REQUEST\x10\x96\x01\x12\x10\n" +
	"\vQUERY_ERROR\x10\x97\x01\x12\x12\n" +
	"\rPROCESS_ERROR\x10\x98\x01\x12\x10\n" +
	"\vBAD_SESSION\x10\x99\x01\x12\x16\n" +
	"\x11LOCKS_INVALIDATED\x10\xaa\x01\x12\x1a\n" +
	"\x15LOCKS_ACQUIRE_FAILURE\x10\xab\x01\x12\x11\n" +
	"\fSCHEME_ERROR\x10\xac\x01\"8\n" +
	"\x0eTUserAttribute\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\tR\x05Value\"\xdf\x04\n" +
	"\x10TDescribeOptions\x12<\n" +
	"\x16ReturnPartitioningInfo\x18\x01 \x01(\b:\x04trueR\x16ReturnPartitioningInfo\x12:\n" +
	"\x15ReturnPartitionConfig\x18\x02 \x01(\b:\x04trueR\x15ReturnPartitionConfig\x12%\n" +
	"\n" +
	"BackupInfo\x18\x03 \x01(\b:\x05falseR\n" +
	"BackupInfo\x129\n" +
	"\x14ReturnPartitionStats\x18\x04 \x01(\b:\x05falseR\x14ReturnPartitionStats\x12,\n" +
	"\x0eReturnChildren\x18\x05 \x01(\b:\x04trueR\x0eReturnChildren\x121\n" +
	"\x10ReturnBoundaries\x18\x06 \x01(\b:\x05falseR\x10ReturnBoundaries\x121\n" +
	"\x10ShowPrivateTable\x18\a \x01(\b:\x05falseR\x10ShowPrivateTable\x12;\n" +
	"\x15ReturnChannelsBinding\x18\b \x01(\b:\x05falseR\x15ReturnChannelsBinding\x12,\n" +
	"\x0eReturnRangeKey\x18\t \x01(\b:\x04trueR\x0eReturnRangeKey\x12)\n" +
	"\fReturnSetVal\x18\n" +
	" \x01(\b:\x05falseR\fReturnSetVal\x12E\n" +
	"\x1aReturnIndexTableBoundaries\x18\v \x01(\b:\x05falseR\x1aReturnIndexTableBoundaries\"Y\n" +
	"\x10TPathDescription\x12E\n" +
	"\x0eUserAttributes\x18\x10 \x03(\v2\x1d.NKikimrClient.TUserAttributeR\x0eUserAttributes\"\xc4\x01\n" +
	"\x0fTSchemeDescribe\x12\x12\n" +
	"\x04Path\x18\x01 \x01(\tR\x04Path\x12\x16\n" +
	"\x06PathId\x18\x02 \x01(\x04R\x06PathId\x12$\n" +
	"\rSchemeshardId\x18\x03 \x01(\x04R\rSchemeshardId\x12$\n" +
	"\rSecurityToken\x18\x05 \x01(\tR\rSecurityToken\x129\n" +
	"\aOptions\x18\x06 \x01(\v2\x1f.NKikimrClient.TDescribeOptionsR\aOptions\"\x9b\x02\n" +
	"\x15TFlatDescribeResponse\x12\x16\n" +
	"\x06Status\x18\x01 \x01(\rR\x06Status\x12I\n" +
	"\x0fPathDescription\x18\x02 \x01(\v2\x1f.NKikimrClient.TPathDescriptionR\x0fPathDescription\x12 \n" +
	"\vErrorReason\x18\x03 \x01(\tR\vErrorReason\x12\"\n" +
	"\fSchemeStatus\x18\x04 \x01(\x05R\fSchemeStatus\x12E\n" +
	"\n" +
	"StatusCode\x18\a \x01(\x0e2%.NKikimrClient.TStatusIds.EStatusCodeR\n" +
	"StatusCode\x12\x12\n" +
	"\x04Path\x18\t \x01(\tR\x04Path2j\n" +
	"\x16TSchemeDescribeService\x12P\n" +
	"\bDescribe\x12\x1e.NKikimrClient.TSchemeDescribe\x1a$.NKikimrClient.TFlatDescribeResponseBa\n" +
	"\x16ru.yandex.kikimr.protoZGgithub.com/ydb-platform/ydbcp/plugins/ydb_nebius/proto;ydb_nebius_proto"

var (
	file_describe_proto_rawDescOnce sync.Once
	file_describe_proto_rawDescData []byte
)

func file_describe_proto_rawDescGZIP() []byte {
	file_describe_proto_rawDescOnce.Do(func() {
		file_describe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_describe_proto_rawDesc), len(file_describe_proto_rawDesc)))
	})
	return file_describe_proto_rawDescData
}

var file_describe_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_describe_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_describe_proto_goTypes = []any{
	(TStatusIds_EStatusCode)(0),   // 0: NKikimrClient.TStatusIds.EStatusCode
	(*TStatusIds)(nil),            // 1: NKikimrClient.TStatusIds
	(*TUserAttribute)(nil),        // 2: NKikimrClient.TUserAttribute
	(*TDescribeOptions)(nil),      // 3: NKikimrClient.TDescribeOptions
	(*TPathDescription)(nil),      // 4: NKikimrClient.TPathDescription
	(*TSchemeDescribe)(nil),       // 5: NKikimrClient.TSchemeDescribe
	(*TFlatDescribeResponse)(nil), // 6: NKikimrClient.TFlatDescribeResponse
}
var file_describe_proto_depIdxs = []int32{
	2, // 0: NKikimrClient.TPathDescription.UserAttributes:type_name -> NKikimrClient.TUserAttribute
	3, // 1: NKikimrClient.TSchemeDescribe.Options:type_name -> NKikimrClient.TDescribeOptions
	4, // 2: NKikimrClient.TFlatDescribeResponse.PathDescription:type_name -> NKikimrClient.TPathDescription
	0, // 3: NKikimrClient.TFlatDescribeResponse.StatusCode:type_name -> NKikimrClient.TStatusIds.EStatusCode
	5, // 4: NKikimrClient.TSchemeDescribeService.Describe:input_type -> NKikimrClient.TSchemeDescribe
	6, // 5: NKikimrClient.TSchemeDescribeService.Describe:output_type -> NKikimrClient.TFlatDescribeResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_describe_proto_init() }
func file_describe_proto_init() {
	if File_describe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_describe_proto_rawDesc), len(file_describe_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_describe_proto_goTypes,
		DependencyIndexes: file_describe_proto_depIdxs,
		EnumInfos:         file_describe_proto_enumTypes,
		MessageInfos:      file_describe_proto_msgTypes,
	}.Build()
	File_describe_proto = out.File
	file_describe_proto_goTypes = nil
	file_describe_proto_depIdxs = nil
}
