// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.1
// source: symmetric_crypto_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	_ "ydbcp/plugins/kms_nebius/proto/nebius"
	_ "ydbcp/plugins/kms_nebius/proto/nebius/audit"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SymmetricEncryptRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the symmetric KMS key to use for encryption.
	KeyId string `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// Additional authenticated data (AAD context), optional.
	// If specified, this data will be required for decryption with the [SymmetricDecryptRequest].
	// Should be encoded with base64.
	AadContext []byte `protobuf:"bytes,2,opt,name=aad_context,json=aadContext,proto3" json:"aad_context,omitempty"`
	// Plaintext to be encrypted.
	// Should be encoded with base64.
	Plaintext     []byte `protobuf:"bytes,3,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymmetricEncryptRequest) Reset() {
	*x = SymmetricEncryptRequest{}
	mi := &file_symmetric_crypto_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymmetricEncryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymmetricEncryptRequest) ProtoMessage() {}

func (x *SymmetricEncryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_symmetric_crypto_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymmetricEncryptRequest.ProtoReflect.Descriptor instead.
func (*SymmetricEncryptRequest) Descriptor() ([]byte, []int) {
	return file_symmetric_crypto_service_proto_rawDescGZIP(), []int{0}
}

func (x *SymmetricEncryptRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SymmetricEncryptRequest) GetAadContext() []byte {
	if x != nil {
		return x.AadContext
	}
	return nil
}

func (x *SymmetricEncryptRequest) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

type SymmetricEncryptResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the symmetric KMS key that was used for encryption.
	KeyId string `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// Resulting ciphertext.
	Ciphertext    []byte `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymmetricEncryptResponse) Reset() {
	*x = SymmetricEncryptResponse{}
	mi := &file_symmetric_crypto_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymmetricEncryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymmetricEncryptResponse) ProtoMessage() {}

func (x *SymmetricEncryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_symmetric_crypto_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymmetricEncryptResponse.ProtoReflect.Descriptor instead.
func (*SymmetricEncryptResponse) Descriptor() ([]byte, []int) {
	return file_symmetric_crypto_service_proto_rawDescGZIP(), []int{1}
}

func (x *SymmetricEncryptResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SymmetricEncryptResponse) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

type SymmetricDecryptRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the symmetric KMS key to use for decryption.
	KeyId string `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// Additional authenticated data, must be the same as was provided
	// in the corresponding [SymmetricEncryptRequest].
	// Should be encoded with base64.
	AadContext []byte `protobuf:"bytes,2,opt,name=aad_context,json=aadContext,proto3" json:"aad_context,omitempty"`
	// Ciphertext to be decrypted.
	// Should be encoded with base64.
	Ciphertext    []byte `protobuf:"bytes,3,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymmetricDecryptRequest) Reset() {
	*x = SymmetricDecryptRequest{}
	mi := &file_symmetric_crypto_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymmetricDecryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymmetricDecryptRequest) ProtoMessage() {}

func (x *SymmetricDecryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_symmetric_crypto_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymmetricDecryptRequest.ProtoReflect.Descriptor instead.
func (*SymmetricDecryptRequest) Descriptor() ([]byte, []int) {
	return file_symmetric_crypto_service_proto_rawDescGZIP(), []int{2}
}

func (x *SymmetricDecryptRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SymmetricDecryptRequest) GetAadContext() []byte {
	if x != nil {
		return x.AadContext
	}
	return nil
}

func (x *SymmetricDecryptRequest) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

type SymmetricDecryptResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the symmetric KMS key that was used for decryption.
	KeyId string `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// Decrypted plaintext.
	Plaintext     []byte `protobuf:"bytes,2,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymmetricDecryptResponse) Reset() {
	*x = SymmetricDecryptResponse{}
	mi := &file_symmetric_crypto_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymmetricDecryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymmetricDecryptResponse) ProtoMessage() {}

func (x *SymmetricDecryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_symmetric_crypto_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymmetricDecryptResponse.ProtoReflect.Descriptor instead.
func (*SymmetricDecryptResponse) Descriptor() ([]byte, []int) {
	return file_symmetric_crypto_service_proto_rawDescGZIP(), []int{3}
}

func (x *SymmetricDecryptResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SymmetricDecryptResponse) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

var File_symmetric_crypto_service_proto protoreflect.FileDescriptor

const file_symmetric_crypto_service_proto_rawDesc = "" +
	"\n" +
	"\x1esymmetric_crypto_service.proto\x12\rnebius.kms.v1\x1a\x18nebius/annotations.proto\x1a\x1enebius/audit/annotations.proto\"y\n" +
	"\x17SymmetricEncryptRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12$\n" +
	"\vaad_context\x18\x02 \x01(\fB\x03\xc0J\x01R\n" +
	"aadContext\x12!\n" +
	"\tplaintext\x18\x03 \x01(\fB\x03\xc0J\x01R\tplaintext\"V\n" +
	"\x18SymmetricEncryptResponse\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12#\n" +
	"\n" +
	"ciphertext\x18\x02 \x01(\fB\x03\xc0J\x01R\n" +
	"ciphertext\"{\n" +
	"\x17SymmetricDecryptRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12$\n" +
	"\vaad_context\x18\x02 \x01(\fB\x03\xc0J\x01R\n" +
	"aadContext\x12#\n" +
	"\n" +
	"ciphertext\x18\x03 \x01(\fB\x03\xc0J\x01R\n" +
	"ciphertext\"T\n" +
	"\x18SymmetricDecryptResponse\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12!\n" +
	"\tplaintext\x18\x02 \x01(\fB\x03\xc0J\x01R\tplaintext2\xac\x02\n" +
	"\x16SymmetricCryptoService\x12\x7f\n" +
	"\aEncrypt\x12&.nebius.kms.v1.SymmetricEncryptRequest\x1a'.nebius.kms.v1.SymmetricEncryptResponse\"#\x92\xb5\x18\x11\n" +
	"\x0f\x1a\r\x10\x18\n" +
	"\tkmssymkey\x9a\xb5\x18\n" +
	"\n" +
	"\x06key_id\x18\x01\x12\x7f\n" +
	"\aDecrypt\x12&.nebius.kms.v1.SymmetricDecryptRequest\x1a'.nebius.kms.v1.SymmetricDecryptResponse\"#\x92\xb5\x18\x11\n" +
	"\x0f\x1a\r\x10\x19\n" +
	"\tkmssymkey\x9a\xb5\x18\n" +
	"\n" +
	"\x06key_id\x18\x01\x1a\x10\xbaJ\adpl.kms\xa2\xb5\x18\x02\b\x01BQ\n" +
	"\x10ai.nebius.kms.v1B\x1bSymmetricCryptoServiceProtoP\x01Z\x1eydbcp/plugins/kms_nebius/protob\x06proto3"

var (
	file_symmetric_crypto_service_proto_rawDescOnce sync.Once
	file_symmetric_crypto_service_proto_rawDescData []byte
)

func file_symmetric_crypto_service_proto_rawDescGZIP() []byte {
	file_symmetric_crypto_service_proto_rawDescOnce.Do(func() {
		file_symmetric_crypto_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_symmetric_crypto_service_proto_rawDesc), len(file_symmetric_crypto_service_proto_rawDesc)))
	})
	return file_symmetric_crypto_service_proto_rawDescData
}

var file_symmetric_crypto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_symmetric_crypto_service_proto_goTypes = []any{
	(*SymmetricEncryptRequest)(nil),  // 0: nebius.kms.v1.SymmetricEncryptRequest
	(*SymmetricEncryptResponse)(nil), // 1: nebius.kms.v1.SymmetricEncryptResponse
	(*SymmetricDecryptRequest)(nil),  // 2: nebius.kms.v1.SymmetricDecryptRequest
	(*SymmetricDecryptResponse)(nil), // 3: nebius.kms.v1.SymmetricDecryptResponse
}
var file_symmetric_crypto_service_proto_depIdxs = []int32{
	0, // 0: nebius.kms.v1.SymmetricCryptoService.Encrypt:input_type -> nebius.kms.v1.SymmetricEncryptRequest
	2, // 1: nebius.kms.v1.SymmetricCryptoService.Decrypt:input_type -> nebius.kms.v1.SymmetricDecryptRequest
	1, // 2: nebius.kms.v1.SymmetricCryptoService.Encrypt:output_type -> nebius.kms.v1.SymmetricEncryptResponse
	3, // 3: nebius.kms.v1.SymmetricCryptoService.Decrypt:output_type -> nebius.kms.v1.SymmetricDecryptResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_symmetric_crypto_service_proto_init() }
func file_symmetric_crypto_service_proto_init() {
	if File_symmetric_crypto_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_symmetric_crypto_service_proto_rawDesc), len(file_symmetric_crypto_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_symmetric_crypto_service_proto_goTypes,
		DependencyIndexes: file_symmetric_crypto_service_proto_depIdxs,
		MessageInfos:      file_symmetric_crypto_service_proto_msgTypes,
	}.Build()
	File_symmetric_crypto_service_proto = out.File
	file_symmetric_crypto_service_proto_goTypes = nil
	file_symmetric_crypto_service_proto_depIdxs = nil
}
