// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: iam/v1/access.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*Account_UserAccount_
	//	*Account_ServiceAccount_
	//	*Account_AnonymousAccount_
	Type isAccount_Type `protobuf_oneof:"type"`
}

func (x *Account) Reset() {
	*x = Account{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iam_v1_access_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_access_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_iam_v1_access_proto_rawDescGZIP(), []int{0}
}

func (m *Account) GetType() isAccount_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Account) GetUserAccount() *Account_UserAccount {
	if x, ok := x.GetType().(*Account_UserAccount_); ok {
		return x.UserAccount
	}
	return nil
}

func (x *Account) GetServiceAccount() *Account_ServiceAccount {
	if x, ok := x.GetType().(*Account_ServiceAccount_); ok {
		return x.ServiceAccount
	}
	return nil
}

func (x *Account) GetAnonymousAccount() *Account_AnonymousAccount {
	if x, ok := x.GetType().(*Account_AnonymousAccount_); ok {
		return x.AnonymousAccount
	}
	return nil
}

type isAccount_Type interface {
	isAccount_Type()
}

type Account_UserAccount_ struct {
	UserAccount *Account_UserAccount `protobuf:"bytes,1,opt,name=user_account,json=userAccount,proto3,oneof"`
}

type Account_ServiceAccount_ struct {
	ServiceAccount *Account_ServiceAccount `protobuf:"bytes,2,opt,name=service_account,json=serviceAccount,proto3,oneof"`
}

type Account_AnonymousAccount_ struct {
	AnonymousAccount *Account_AnonymousAccount `protobuf:"bytes,3,opt,name=anonymous_account,json=anonymousAccount,proto3,oneof"`
}

func (*Account_UserAccount_) isAccount_Type() {}

func (*Account_ServiceAccount_) isAccount_Type() {}

func (*Account_AnonymousAccount_) isAccount_Type() {}

type Permission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Permission) Reset() {
	*x = Permission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iam_v1_access_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_access_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_iam_v1_access_proto_rawDescGZIP(), []int{1}
}

func (x *Permission) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Resource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Resource) Reset() {
	*x = Resource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iam_v1_access_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_access_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_iam_v1_access_proto_rawDescGZIP(), []int{2}
}

func (x *Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResourcePath struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path []*Resource `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
}

func (x *ResourcePath) Reset() {
	*x = ResourcePath{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iam_v1_access_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourcePath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcePath) ProtoMessage() {}

func (x *ResourcePath) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_access_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcePath.ProtoReflect.Descriptor instead.
func (*ResourcePath) Descriptor() ([]byte, []int) {
	return file_iam_v1_access_proto_rawDescGZIP(), []int{3}
}

func (x *ResourcePath) GetPath() []*Resource {
	if x != nil {
		return x.Path
	}
	return nil
}

type Account_UserAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Account_UserAccount) Reset() {
	*x = Account_UserAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iam_v1_access_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Account_UserAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account_UserAccount) ProtoMessage() {}

func (x *Account_UserAccount) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_access_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account_UserAccount.ProtoReflect.Descriptor instead.
func (*Account_UserAccount) Descriptor() ([]byte, []int) {
	return file_iam_v1_access_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Account_UserAccount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Account_ServiceAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Account_ServiceAccount) Reset() {
	*x = Account_ServiceAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iam_v1_access_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Account_ServiceAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account_ServiceAccount) ProtoMessage() {}

func (x *Account_ServiceAccount) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_access_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account_ServiceAccount.ProtoReflect.Descriptor instead.
func (*Account_ServiceAccount) Descriptor() ([]byte, []int) {
	return file_iam_v1_access_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Account_ServiceAccount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Account_AnonymousAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Account_AnonymousAccount) Reset() {
	*x = Account_AnonymousAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_iam_v1_access_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Account_AnonymousAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account_AnonymousAccount) ProtoMessage() {}

func (x *Account_AnonymousAccount) ProtoReflect() protoreflect.Message {
	mi := &file_iam_v1_access_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account_AnonymousAccount.ProtoReflect.Descriptor instead.
func (*Account_AnonymousAccount) Descriptor() ([]byte, []int) {
	return file_iam_v1_access_proto_rawDescGZIP(), []int{0, 2}
}

var File_iam_v1_access_proto protoreflect.FileDescriptor

var file_iam_v1_access_proto_rawDesc = []byte{
	0x0a, 0x13, 0x69, 0x61, 0x6d, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6e, 0x65, 0x62, 0x69, 0x75, 0x73, 0x2e, 0x69, 0x61,
	0x6d, 0x2e, 0x76, 0x31, 0x22, 0xd9, 0x02, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x47, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6e, 0x65, 0x62, 0x69, 0x75, 0x73, 0x2e,
	0x69, 0x61, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x75, 0x73,
	0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x50, 0x0a, 0x0f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6e, 0x65, 0x62, 0x69, 0x75, 0x73, 0x2e, 0x69, 0x61, 0x6d, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x56, 0x0a, 0x11, 0x61,
	0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6e, 0x65, 0x62, 0x69, 0x75, 0x73, 0x2e,
	0x69, 0x61, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x41,
	0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x48,
	0x00, 0x52, 0x10, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x1a, 0x1d, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x1a, 0x20, 0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x1a, 0x12, 0x0a, 0x10, 0x41, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75,
	0x73, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x22, 0x20, 0x0a, 0x0a, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3b,
	0x0a, 0x0c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x2b,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6e,
	0x65, 0x62, 0x69, 0x75, 0x73, 0x2e, 0x69, 0x61, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x42, 0x65, 0x0a, 0x20, 0x61,
	0x69, 0x2e, 0x6e, 0x65, 0x62, 0x69, 0x75, 0x73, 0x2e, 0x69, 0x61, 0x6d, 0x2e, 0x61, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x69, 0x76, 0x2e, 0x76, 0x31, 0x42,
	0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x32,
	0x61, 0x2e, 0x79, 0x61, 0x6e, 0x64, 0x65, 0x78, 0x2d, 0x74, 0x65, 0x61, 0x6d, 0x2e, 0x72, 0x75,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6e, 0x65, 0x62, 0x69, 0x75, 0x73, 0x2d, 0x61, 0x69, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x65, 0x62, 0x69, 0x75, 0x73, 0x2f, 0x69, 0x61, 0x6d, 0x2f,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_iam_v1_access_proto_rawDescOnce sync.Once
	file_iam_v1_access_proto_rawDescData = file_iam_v1_access_proto_rawDesc
)

func file_iam_v1_access_proto_rawDescGZIP() []byte {
	file_iam_v1_access_proto_rawDescOnce.Do(func() {
		file_iam_v1_access_proto_rawDescData = protoimpl.X.CompressGZIP(file_iam_v1_access_proto_rawDescData)
	})
	return file_iam_v1_access_proto_rawDescData
}

var file_iam_v1_access_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_iam_v1_access_proto_goTypes = []any{
	(*Account)(nil),                  // 0: nebius.iam.v1.Account
	(*Permission)(nil),               // 1: nebius.iam.v1.Permission
	(*Resource)(nil),                 // 2: nebius.iam.v1.Resource
	(*ResourcePath)(nil),             // 3: nebius.iam.v1.ResourcePath
	(*Account_UserAccount)(nil),      // 4: nebius.iam.v1.Account.UserAccount
	(*Account_ServiceAccount)(nil),   // 5: nebius.iam.v1.Account.ServiceAccount
	(*Account_AnonymousAccount)(nil), // 6: nebius.iam.v1.Account.AnonymousAccount
}
var file_iam_v1_access_proto_depIdxs = []int32{
	4, // 0: nebius.iam.v1.Account.user_account:type_name -> nebius.iam.v1.Account.UserAccount
	5, // 1: nebius.iam.v1.Account.service_account:type_name -> nebius.iam.v1.Account.ServiceAccount
	6, // 2: nebius.iam.v1.Account.anonymous_account:type_name -> nebius.iam.v1.Account.AnonymousAccount
	2, // 3: nebius.iam.v1.ResourcePath.path:type_name -> nebius.iam.v1.Resource
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_iam_v1_access_proto_init() }
func file_iam_v1_access_proto_init() {
	if File_iam_v1_access_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_iam_v1_access_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Account); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iam_v1_access_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Permission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iam_v1_access_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Resource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iam_v1_access_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ResourcePath); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iam_v1_access_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Account_UserAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iam_v1_access_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Account_ServiceAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_iam_v1_access_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*Account_AnonymousAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_iam_v1_access_proto_msgTypes[0].OneofWrappers = []any{
		(*Account_UserAccount_)(nil),
		(*Account_ServiceAccount_)(nil),
		(*Account_AnonymousAccount_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_iam_v1_access_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_iam_v1_access_proto_goTypes,
		DependencyIndexes: file_iam_v1_access_proto_depIdxs,
		MessageInfos:      file_iam_v1_access_proto_msgTypes,
	}.Build()
	File_iam_v1_access_proto = out.File
	file_iam_v1_access_proto_rawDesc = nil
	file_iam_v1_access_proto_goTypes = nil
	file_iam_v1_access_proto_depIdxs = nil
}
