// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: ydb_nebius/describe.proto

// Minimal standalone subset matching original legacy gRPC wire contract.

package ydb_nebius_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TGRpcServer_SchemeDescribe_FullMethodName = "/NKikimrClient.TGRpcServer/SchemeDescribe"
)

// TGRpcServerClient is the client API for TGRpcServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Exact legacy service name/method name from grpc.proto.
type TGRpcServerClient interface {
	SchemeDescribe(ctx context.Context, in *TSchemeDescribe, opts ...grpc.CallOption) (*TResponse, error)
}

type tGRpcServerClient struct {
	cc grpc.ClientConnInterface
}

func NewTGRpcServerClient(cc grpc.ClientConnInterface) TGRpcServerClient {
	return &tGRpcServerClient{cc}
}

func (c *tGRpcServerClient) SchemeDescribe(ctx context.Context, in *TSchemeDescribe, opts ...grpc.CallOption) (*TResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TResponse)
	err := c.cc.Invoke(ctx, TGRpcServer_SchemeDescribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TGRpcServerServer is the server API for TGRpcServer service.
// All implementations must embed UnimplementedTGRpcServerServer
// for forward compatibility.
//
// Exact legacy service name/method name from grpc.proto.
type TGRpcServerServer interface {
	SchemeDescribe(context.Context, *TSchemeDescribe) (*TResponse, error)
	mustEmbedUnimplementedTGRpcServerServer()
}

// UnimplementedTGRpcServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTGRpcServerServer struct{}

func (UnimplementedTGRpcServerServer) SchemeDescribe(context.Context, *TSchemeDescribe) (*TResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SchemeDescribe not implemented")
}
func (UnimplementedTGRpcServerServer) mustEmbedUnimplementedTGRpcServerServer() {}
func (UnimplementedTGRpcServerServer) testEmbeddedByValue()                     {}

// UnsafeTGRpcServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TGRpcServerServer will
// result in compilation errors.
type UnsafeTGRpcServerServer interface {
	mustEmbedUnimplementedTGRpcServerServer()
}

func RegisterTGRpcServerServer(s grpc.ServiceRegistrar, srv TGRpcServerServer) {
	// If the following call panics, it indicates UnimplementedTGRpcServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TGRpcServer_ServiceDesc, srv)
}

func _TGRpcServer_SchemeDescribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TSchemeDescribe)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TGRpcServerServer).SchemeDescribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TGRpcServer_SchemeDescribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TGRpcServerServer).SchemeDescribe(ctx, req.(*TSchemeDescribe))
	}
	return interceptor(ctx, in, info, handler)
}

// TGRpcServer_ServiceDesc is the grpc.ServiceDesc for TGRpcServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TGRpcServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "NKikimrClient.TGRpcServer",
	HandlerType: (*TGRpcServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SchemeDescribe",
			Handler:    _TGRpcServer_SchemeDescribe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ydb_nebius/describe.proto",
}
