// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: ydb_nebius/describe.proto

package ydb_nebius_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TSchemeDescribeService_Describe_FullMethodName = "/NKikimrClient.TSchemeDescribeService/Describe"
)

// TSchemeDescribeServiceClient is the client API for TSchemeDescribeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TSchemeDescribeServiceClient interface {
	Describe(ctx context.Context, in *TSchemeDescribe, opts ...grpc.CallOption) (*TFlatDescribeResponse, error)
}

type tSchemeDescribeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTSchemeDescribeServiceClient(cc grpc.ClientConnInterface) TSchemeDescribeServiceClient {
	return &tSchemeDescribeServiceClient{cc}
}

func (c *tSchemeDescribeServiceClient) Describe(ctx context.Context, in *TSchemeDescribe, opts ...grpc.CallOption) (*TFlatDescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TFlatDescribeResponse)
	err := c.cc.Invoke(ctx, TSchemeDescribeService_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TSchemeDescribeServiceServer is the server API for TSchemeDescribeService service.
// All implementations must embed UnimplementedTSchemeDescribeServiceServer
// for forward compatibility.
type TSchemeDescribeServiceServer interface {
	Describe(context.Context, *TSchemeDescribe) (*TFlatDescribeResponse, error)
	mustEmbedUnimplementedTSchemeDescribeServiceServer()
}

// UnimplementedTSchemeDescribeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTSchemeDescribeServiceServer struct{}

func (UnimplementedTSchemeDescribeServiceServer) Describe(context.Context, *TSchemeDescribe) (*TFlatDescribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedTSchemeDescribeServiceServer) mustEmbedUnimplementedTSchemeDescribeServiceServer() {
}
func (UnimplementedTSchemeDescribeServiceServer) testEmbeddedByValue() {}

// UnsafeTSchemeDescribeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TSchemeDescribeServiceServer will
// result in compilation errors.
type UnsafeTSchemeDescribeServiceServer interface {
	mustEmbedUnimplementedTSchemeDescribeServiceServer()
}

func RegisterTSchemeDescribeServiceServer(s grpc.ServiceRegistrar, srv TSchemeDescribeServiceServer) {
	// If the following call panics, it indicates UnimplementedTSchemeDescribeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TSchemeDescribeService_ServiceDesc, srv)
}

func _TSchemeDescribeService_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TSchemeDescribe)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TSchemeDescribeServiceServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TSchemeDescribeService_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TSchemeDescribeServiceServer).Describe(ctx, req.(*TSchemeDescribe))
	}
	return interceptor(ctx, in, info, handler)
}

// TSchemeDescribeService_ServiceDesc is the grpc.ServiceDesc for TSchemeDescribeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TSchemeDescribeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "NKikimrClient.TSchemeDescribeService",
	HandlerType: (*TSchemeDescribeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _TSchemeDescribeService_Describe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ydb_nebius/describe.proto",
}
