// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.1
// source: nebius/annotations.proto

package nebius

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegionRouting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nid           []string               `protobuf:"bytes,1,rep,name=nid,proto3" json:"nid,omitempty"`
	Strict        bool                   `protobuf:"varint,3,opt,name=strict,proto3" json:"strict,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionRouting) Reset() {
	*x = RegionRouting{}
	mi := &file_nebius_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionRouting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionRouting) ProtoMessage() {}

func (x *RegionRouting) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionRouting.ProtoReflect.Descriptor instead.
func (*RegionRouting) Descriptor() ([]byte, []int) {
	return file_nebius_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *RegionRouting) GetNid() []string {
	if x != nil {
		return x.Nid
	}
	return nil
}

func (x *RegionRouting) GetStrict() bool {
	if x != nil {
		return x.Strict
	}
	return false
}

var file_nebius_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         1191,
		Name:          "nebius.api_service_name",
		Tag:           "bytes,1191,opt,name=api_service_name",
		Filename:      "nebius/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*RegionRouting)(nil),
		Field:         50003,
		Name:          "nebius.region_routing",
		Tag:           "bytes,50003,opt,name=region_routing",
		Filename:      "nebius/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1192,
		Name:          "nebius.sensitive",
		Tag:           "varint,1192,opt,name=sensitive",
		Filename:      "nebius/annotations.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional string api_service_name = 1191;
	E_ApiServiceName = &file_nebius_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional nebius.RegionRouting region_routing = 50003;
	E_RegionRouting = &file_nebius_annotations_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool sensitive = 1192;
	E_Sensitive = &file_nebius_annotations_proto_extTypes[2]
)

var File_nebius_annotations_proto protoreflect.FileDescriptor

const file_nebius_annotations_proto_rawDesc = "" +
	"\n" +
	"\x18nebius/annotations.proto\x12\x06nebius\x1a google/protobuf/descriptor.proto\"9\n" +
	"\rRegionRouting\x12\x10\n" +
	"\x03nid\x18\x01 \x03(\tR\x03nid\x12\x16\n" +
	"\x06strict\x18\x03 \x01(\bR\x06strict:J\n" +
	"\x10api_service_name\x12\x1f.google.protobuf.ServiceOptions\x18\xa7\t \x01(\tR\x0eapiServiceName:^\n" +
	"\x0eregion_routing\x12\x1e.google.protobuf.MethodOptions\x18ӆ\x03 \x01(\v2\x15.nebius.RegionRoutingR\rregionRouting:<\n" +
	"\tsensitive\x12\x1d.google.protobuf.FieldOptions\x18\xa8\t \x01(\bR\tsensitiveBF\n" +
	"\tai.nebiusB\x10AnnotationsProtoP\x01Z%ydbcp/plugins/kms_nebius/proto/nebiusb\x06proto3"

var (
	file_nebius_annotations_proto_rawDescOnce sync.Once
	file_nebius_annotations_proto_rawDescData []byte
)

func file_nebius_annotations_proto_rawDescGZIP() []byte {
	file_nebius_annotations_proto_rawDescOnce.Do(func() {
		file_nebius_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nebius_annotations_proto_rawDesc), len(file_nebius_annotations_proto_rawDesc)))
	})
	return file_nebius_annotations_proto_rawDescData
}

var file_nebius_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_nebius_annotations_proto_goTypes = []any{
	(*RegionRouting)(nil),               // 0: nebius.RegionRouting
	(*descriptorpb.ServiceOptions)(nil), // 1: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 2: google.protobuf.MethodOptions
	(*descriptorpb.FieldOptions)(nil),   // 3: google.protobuf.FieldOptions
}
var file_nebius_annotations_proto_depIdxs = []int32{
	1, // 0: nebius.api_service_name:extendee -> google.protobuf.ServiceOptions
	2, // 1: nebius.region_routing:extendee -> google.protobuf.MethodOptions
	3, // 2: nebius.sensitive:extendee -> google.protobuf.FieldOptions
	0, // 3: nebius.region_routing:type_name -> nebius.RegionRouting
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	3, // [3:4] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nebius_annotations_proto_init() }
func file_nebius_annotations_proto_init() {
	if File_nebius_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nebius_annotations_proto_rawDesc), len(file_nebius_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_nebius_annotations_proto_goTypes,
		DependencyIndexes: file_nebius_annotations_proto_depIdxs,
		MessageInfos:      file_nebius_annotations_proto_msgTypes,
		ExtensionInfos:    file_nebius_annotations_proto_extTypes,
	}.Build()
	File_nebius_annotations_proto = out.File
	file_nebius_annotations_proto_goTypes = nil
	file_nebius_annotations_proto_depIdxs = nil
}
