// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.1
// source: nebius/audit/annotations.proto

package audit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	common "ydbcp/plugins/kms_nebius/proto/nebius/audit/v1/common"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MethodAuditMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Activities:
	//
	//	*MethodAuditMetadata_ResourceType
	//	*MethodAuditMetadata_DefaultActivity
	Activities    isMethodAuditMetadata_Activities `protobuf_oneof:"activities"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodAuditMetadata) Reset() {
	*x = MethodAuditMetadata{}
	mi := &file_nebius_audit_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodAuditMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodAuditMetadata) ProtoMessage() {}

func (x *MethodAuditMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_audit_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodAuditMetadata.ProtoReflect.Descriptor instead.
func (*MethodAuditMetadata) Descriptor() ([]byte, []int) {
	return file_nebius_audit_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *MethodAuditMetadata) GetActivities() isMethodAuditMetadata_Activities {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *MethodAuditMetadata) GetResourceType() string {
	if x != nil {
		if x, ok := x.Activities.(*MethodAuditMetadata_ResourceType); ok {
			return x.ResourceType
		}
	}
	return ""
}

func (x *MethodAuditMetadata) GetDefaultActivity() *AuditedActivity {
	if x != nil {
		if x, ok := x.Activities.(*MethodAuditMetadata_DefaultActivity); ok {
			return x.DefaultActivity
		}
	}
	return nil
}

type isMethodAuditMetadata_Activities interface {
	isMethodAuditMetadata_Activities()
}

type MethodAuditMetadata_ResourceType struct {
	ResourceType string `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3,oneof"`
}

type MethodAuditMetadata_DefaultActivity struct {
	DefaultActivity *AuditedActivity `protobuf:"bytes,3,opt,name=default_activity,json=defaultActivity,proto3,oneof"`
}

func (*MethodAuditMetadata_ResourceType) isMethodAuditMetadata_Activities() {}

func (*MethodAuditMetadata_DefaultActivity) isMethodAuditMetadata_Activities() {}

type ServiceAudit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Decision:
	//
	//	*ServiceAudit_Enabled
	Decision      isServiceAudit_Decision `protobuf_oneof:"decision"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceAudit) Reset() {
	*x = ServiceAudit{}
	mi := &file_nebius_audit_annotations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceAudit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAudit) ProtoMessage() {}

func (x *ServiceAudit) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_audit_annotations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAudit.ProtoReflect.Descriptor instead.
func (*ServiceAudit) Descriptor() ([]byte, []int) {
	return file_nebius_audit_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceAudit) GetDecision() isServiceAudit_Decision {
	if x != nil {
		return x.Decision
	}
	return nil
}

func (x *ServiceAudit) GetEnabled() bool {
	if x != nil {
		if x, ok := x.Decision.(*ServiceAudit_Enabled); ok {
			return x.Enabled
		}
	}
	return false
}

type isServiceAudit_Decision interface {
	isServiceAudit_Decision()
}

type ServiceAudit_Enabled struct {
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3,oneof"`
}

func (*ServiceAudit_Enabled) isServiceAudit_Decision() {}

type MethodAudit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Decision:
	//
	//	*MethodAudit_Enabled
	Decision      isMethodAudit_Decision `protobuf_oneof:"decision"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodAudit) Reset() {
	*x = MethodAudit{}
	mi := &file_nebius_audit_annotations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodAudit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodAudit) ProtoMessage() {}

func (x *MethodAudit) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_audit_annotations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodAudit.ProtoReflect.Descriptor instead.
func (*MethodAudit) Descriptor() ([]byte, []int) {
	return file_nebius_audit_annotations_proto_rawDescGZIP(), []int{2}
}

func (x *MethodAudit) GetDecision() isMethodAudit_Decision {
	if x != nil {
		return x.Decision
	}
	return nil
}

func (x *MethodAudit) GetEnabled() *MethodAuditMetadata {
	if x != nil {
		if x, ok := x.Decision.(*MethodAudit_Enabled); ok {
			return x.Enabled
		}
	}
	return nil
}

type isMethodAudit_Decision interface {
	isMethodAudit_Decision()
}

type MethodAudit_Enabled struct {
	Enabled *MethodAuditMetadata `protobuf:"bytes,1,opt,name=enabled,proto3,oneof"`
}

func (*MethodAudit_Enabled) isMethodAudit_Decision() {}

type AuditedActivity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Resource:
	//
	//	*AuditedActivity_ResourceType
	Resource      isAuditedActivity_Resource `protobuf_oneof:"resource"`
	Action        common.Action              `protobuf:"varint,2,opt,name=action,proto3,enum=nebius.audit.v1.common.Action" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditedActivity) Reset() {
	*x = AuditedActivity{}
	mi := &file_nebius_audit_annotations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditedActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditedActivity) ProtoMessage() {}

func (x *AuditedActivity) ProtoReflect() protoreflect.Message {
	mi := &file_nebius_audit_annotations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditedActivity.ProtoReflect.Descriptor instead.
func (*AuditedActivity) Descriptor() ([]byte, []int) {
	return file_nebius_audit_annotations_proto_rawDescGZIP(), []int{3}
}

func (x *AuditedActivity) GetResource() isAuditedActivity_Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *AuditedActivity) GetResourceType() string {
	if x != nil {
		if x, ok := x.Resource.(*AuditedActivity_ResourceType); ok {
			return x.ResourceType
		}
	}
	return ""
}

func (x *AuditedActivity) GetAction() common.Action {
	if x != nil {
		return x.Action
	}
	return common.Action(0)
}

type isAuditedActivity_Resource interface {
	isAuditedActivity_Resource()
}

type AuditedActivity_ResourceType struct {
	ResourceType string `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3,oneof"`
}

func (*AuditedActivity_ResourceType) isAuditedActivity_Resource() {}

var file_nebius_audit_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ServiceAudit)(nil),
		Field:         50004,
		Name:          "nebius.audit.service_audit",
		Tag:           "bytes,50004,opt,name=service_audit",
		Filename:      "nebius/audit/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MethodAudit)(nil),
		Field:         50002,
		Name:          "nebius.audit.method_audit",
		Tag:           "bytes,50002,opt,name=method_audit",
		Filename:      "nebius/audit/annotations.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional nebius.audit.ServiceAudit service_audit = 50004;
	E_ServiceAudit = &file_nebius_audit_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional nebius.audit.MethodAudit method_audit = 50002;
	E_MethodAudit = &file_nebius_audit_annotations_proto_extTypes[1]
)

var File_nebius_audit_annotations_proto protoreflect.FileDescriptor

const file_nebius_audit_annotations_proto_rawDesc = "" +
	"\n" +
	"\x1enebius/audit/annotations.proto\x12\fnebius.audit\x1a google/protobuf/descriptor.proto\x1a#nebius/audit/v1/common/action.proto\"\x96\x01\n" +
	"\x13MethodAuditMetadata\x12%\n" +
	"\rresource_type\x18\x01 \x01(\tH\x00R\fresourceType\x12J\n" +
	"\x10default_activity\x18\x03 \x01(\v2\x1d.nebius.audit.AuditedActivityH\x00R\x0fdefaultActivityB\f\n" +
	"\n" +
	"activities\"6\n" +
	"\fServiceAudit\x12\x1a\n" +
	"\aenabled\x18\x01 \x01(\bH\x00R\aenabledB\n" +
	"\n" +
	"\bdecision\"X\n" +
	"\vMethodAudit\x12=\n" +
	"\aenabled\x18\x01 \x01(\v2!.nebius.audit.MethodAuditMetadataH\x00R\aenabledB\n" +
	"\n" +
	"\bdecision\"|\n" +
	"\x0fAuditedActivity\x12%\n" +
	"\rresource_type\x18\x01 \x01(\tH\x00R\fresourceType\x126\n" +
	"\x06action\x18\x02 \x01(\x0e2\x1e.nebius.audit.v1.common.ActionR\x06actionB\n" +
	"\n" +
	"\bresource:b\n" +
	"\rservice_audit\x12\x1f.google.protobuf.ServiceOptions\x18Ԇ\x03 \x01(\v2\x1a.nebius.audit.ServiceAuditR\fserviceAudit:^\n" +
	"\fmethod_audit\x12\x1e.google.protobuf.MethodOptions\x18҆\x03 \x01(\v2\x19.nebius.audit.MethodAuditR\vmethodAuditBR\n" +
	"\x0fai.nebius.auditB\x10AnnotationsProtoP\x01Z+ydbcp/plugins/kms_nebius/proto/nebius/auditb\x06proto3"

var (
	file_nebius_audit_annotations_proto_rawDescOnce sync.Once
	file_nebius_audit_annotations_proto_rawDescData []byte
)

func file_nebius_audit_annotations_proto_rawDescGZIP() []byte {
	file_nebius_audit_annotations_proto_rawDescOnce.Do(func() {
		file_nebius_audit_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nebius_audit_annotations_proto_rawDesc), len(file_nebius_audit_annotations_proto_rawDesc)))
	})
	return file_nebius_audit_annotations_proto_rawDescData
}

var file_nebius_audit_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_nebius_audit_annotations_proto_goTypes = []any{
	(*MethodAuditMetadata)(nil),         // 0: nebius.audit.MethodAuditMetadata
	(*ServiceAudit)(nil),                // 1: nebius.audit.ServiceAudit
	(*MethodAudit)(nil),                 // 2: nebius.audit.MethodAudit
	(*AuditedActivity)(nil),             // 3: nebius.audit.AuditedActivity
	(common.Action)(0),                  // 4: nebius.audit.v1.common.Action
	(*descriptorpb.ServiceOptions)(nil), // 5: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 6: google.protobuf.MethodOptions
}
var file_nebius_audit_annotations_proto_depIdxs = []int32{
	3, // 0: nebius.audit.MethodAuditMetadata.default_activity:type_name -> nebius.audit.AuditedActivity
	0, // 1: nebius.audit.MethodAudit.enabled:type_name -> nebius.audit.MethodAuditMetadata
	4, // 2: nebius.audit.AuditedActivity.action:type_name -> nebius.audit.v1.common.Action
	5, // 3: nebius.audit.service_audit:extendee -> google.protobuf.ServiceOptions
	6, // 4: nebius.audit.method_audit:extendee -> google.protobuf.MethodOptions
	1, // 5: nebius.audit.service_audit:type_name -> nebius.audit.ServiceAudit
	2, // 6: nebius.audit.method_audit:type_name -> nebius.audit.MethodAudit
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	5, // [5:7] is the sub-list for extension type_name
	3, // [3:5] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_nebius_audit_annotations_proto_init() }
func file_nebius_audit_annotations_proto_init() {
	if File_nebius_audit_annotations_proto != nil {
		return
	}
	file_nebius_audit_annotations_proto_msgTypes[0].OneofWrappers = []any{
		(*MethodAuditMetadata_ResourceType)(nil),
		(*MethodAuditMetadata_DefaultActivity)(nil),
	}
	file_nebius_audit_annotations_proto_msgTypes[1].OneofWrappers = []any{
		(*ServiceAudit_Enabled)(nil),
	}
	file_nebius_audit_annotations_proto_msgTypes[2].OneofWrappers = []any{
		(*MethodAudit_Enabled)(nil),
	}
	file_nebius_audit_annotations_proto_msgTypes[3].OneofWrappers = []any{
		(*AuditedActivity_ResourceType)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nebius_audit_annotations_proto_rawDesc), len(file_nebius_audit_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_nebius_audit_annotations_proto_goTypes,
		DependencyIndexes: file_nebius_audit_annotations_proto_depIdxs,
		MessageInfos:      file_nebius_audit_annotations_proto_msgTypes,
		ExtensionInfos:    file_nebius_audit_annotations_proto_extTypes,
	}.Build()
	File_nebius_audit_annotations_proto = out.File
	file_nebius_audit_annotations_proto_goTypes = nil
	file_nebius_audit_annotations_proto_depIdxs = nil
}
