// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: ydbcp/v1alpha1/backup_schedule_service.proto

package ydbcp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BackupScheduleService_SetBackupSchedule_FullMethodName        = "/ydbcp.BackupScheduleService/SetBackupSchedule"
	BackupScheduleService_GetBackupSchedule_FullMethodName        = "/ydbcp.BackupScheduleService/GetBackupSchedule"
	BackupScheduleService_ListBackupSchedules_FullMethodName      = "/ydbcp.BackupScheduleService/ListBackupSchedules"
	BackupScheduleService_ActivateBackupSchedule_FullMethodName   = "/ydbcp.BackupScheduleService/ActivateBackupSchedule"
	BackupScheduleService_DeactivateBackupSchedule_FullMethodName = "/ydbcp.BackupScheduleService/DeactivateBackupSchedule"
)

// BackupScheduleServiceClient is the client API for BackupScheduleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BackupScheduleServiceClient interface {
	SetBackupSchedule(ctx context.Context, in *SetBackupScheduleRequest, opts ...grpc.CallOption) (*BackupSchedule, error)
	GetBackupSchedule(ctx context.Context, in *GetBackupScheduleRequest, opts ...grpc.CallOption) (*BackupSchedule, error)
	ListBackupSchedules(ctx context.Context, in *ListBackupSchedulesRequest, opts ...grpc.CallOption) (*ListBackupSchedulesResponse, error)
	ActivateBackupSchedule(ctx context.Context, in *ToggleBackupScheduleRequest, opts ...grpc.CallOption) (*BackupSchedule, error)
	DeactivateBackupSchedule(ctx context.Context, in *ToggleBackupScheduleRequest, opts ...grpc.CallOption) (*BackupSchedule, error)
}

type backupScheduleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBackupScheduleServiceClient(cc grpc.ClientConnInterface) BackupScheduleServiceClient {
	return &backupScheduleServiceClient{cc}
}

func (c *backupScheduleServiceClient) SetBackupSchedule(ctx context.Context, in *SetBackupScheduleRequest, opts ...grpc.CallOption) (*BackupSchedule, error) {
	out := new(BackupSchedule)
	err := c.cc.Invoke(ctx, BackupScheduleService_SetBackupSchedule_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupScheduleServiceClient) GetBackupSchedule(ctx context.Context, in *GetBackupScheduleRequest, opts ...grpc.CallOption) (*BackupSchedule, error) {
	out := new(BackupSchedule)
	err := c.cc.Invoke(ctx, BackupScheduleService_GetBackupSchedule_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupScheduleServiceClient) ListBackupSchedules(ctx context.Context, in *ListBackupSchedulesRequest, opts ...grpc.CallOption) (*ListBackupSchedulesResponse, error) {
	out := new(ListBackupSchedulesResponse)
	err := c.cc.Invoke(ctx, BackupScheduleService_ListBackupSchedules_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupScheduleServiceClient) ActivateBackupSchedule(ctx context.Context, in *ToggleBackupScheduleRequest, opts ...grpc.CallOption) (*BackupSchedule, error) {
	out := new(BackupSchedule)
	err := c.cc.Invoke(ctx, BackupScheduleService_ActivateBackupSchedule_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupScheduleServiceClient) DeactivateBackupSchedule(ctx context.Context, in *ToggleBackupScheduleRequest, opts ...grpc.CallOption) (*BackupSchedule, error) {
	out := new(BackupSchedule)
	err := c.cc.Invoke(ctx, BackupScheduleService_DeactivateBackupSchedule_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackupScheduleServiceServer is the server API for BackupScheduleService service.
// All implementations must embed UnimplementedBackupScheduleServiceServer
// for forward compatibility
type BackupScheduleServiceServer interface {
	SetBackupSchedule(context.Context, *SetBackupScheduleRequest) (*BackupSchedule, error)
	GetBackupSchedule(context.Context, *GetBackupScheduleRequest) (*BackupSchedule, error)
	ListBackupSchedules(context.Context, *ListBackupSchedulesRequest) (*ListBackupSchedulesResponse, error)
	ActivateBackupSchedule(context.Context, *ToggleBackupScheduleRequest) (*BackupSchedule, error)
	DeactivateBackupSchedule(context.Context, *ToggleBackupScheduleRequest) (*BackupSchedule, error)
	mustEmbedUnimplementedBackupScheduleServiceServer()
}

// UnimplementedBackupScheduleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBackupScheduleServiceServer struct {
}

func (UnimplementedBackupScheduleServiceServer) SetBackupSchedule(context.Context, *SetBackupScheduleRequest) (*BackupSchedule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetBackupSchedule not implemented")
}
func (UnimplementedBackupScheduleServiceServer) GetBackupSchedule(context.Context, *GetBackupScheduleRequest) (*BackupSchedule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBackupSchedule not implemented")
}
func (UnimplementedBackupScheduleServiceServer) ListBackupSchedules(context.Context, *ListBackupSchedulesRequest) (*ListBackupSchedulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBackupSchedules not implemented")
}
func (UnimplementedBackupScheduleServiceServer) ActivateBackupSchedule(context.Context, *ToggleBackupScheduleRequest) (*BackupSchedule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateBackupSchedule not implemented")
}
func (UnimplementedBackupScheduleServiceServer) DeactivateBackupSchedule(context.Context, *ToggleBackupScheduleRequest) (*BackupSchedule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeactivateBackupSchedule not implemented")
}
func (UnimplementedBackupScheduleServiceServer) mustEmbedUnimplementedBackupScheduleServiceServer() {}

// UnsafeBackupScheduleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackupScheduleServiceServer will
// result in compilation errors.
type UnsafeBackupScheduleServiceServer interface {
	mustEmbedUnimplementedBackupScheduleServiceServer()
}

func RegisterBackupScheduleServiceServer(s grpc.ServiceRegistrar, srv BackupScheduleServiceServer) {
	s.RegisterService(&BackupScheduleService_ServiceDesc, srv)
}

func _BackupScheduleService_SetBackupSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBackupScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupScheduleServiceServer).SetBackupSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupScheduleService_SetBackupSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupScheduleServiceServer).SetBackupSchedule(ctx, req.(*SetBackupScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupScheduleService_GetBackupSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBackupScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupScheduleServiceServer).GetBackupSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupScheduleService_GetBackupSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupScheduleServiceServer).GetBackupSchedule(ctx, req.(*GetBackupScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupScheduleService_ListBackupSchedules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBackupSchedulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupScheduleServiceServer).ListBackupSchedules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupScheduleService_ListBackupSchedules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupScheduleServiceServer).ListBackupSchedules(ctx, req.(*ListBackupSchedulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupScheduleService_ActivateBackupSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleBackupScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupScheduleServiceServer).ActivateBackupSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupScheduleService_ActivateBackupSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupScheduleServiceServer).ActivateBackupSchedule(ctx, req.(*ToggleBackupScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupScheduleService_DeactivateBackupSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleBackupScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupScheduleServiceServer).DeactivateBackupSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackupScheduleService_DeactivateBackupSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupScheduleServiceServer).DeactivateBackupSchedule(ctx, req.(*ToggleBackupScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BackupScheduleService_ServiceDesc is the grpc.ServiceDesc for BackupScheduleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackupScheduleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ydbcp.BackupScheduleService",
	HandlerType: (*BackupScheduleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetBackupSchedule",
			Handler:    _BackupScheduleService_SetBackupSchedule_Handler,
		},
		{
			MethodName: "GetBackupSchedule",
			Handler:    _BackupScheduleService_GetBackupSchedule_Handler,
		},
		{
			MethodName: "ListBackupSchedules",
			Handler:    _BackupScheduleService_ListBackupSchedules_Handler,
		},
		{
			MethodName: "ActivateBackupSchedule",
			Handler:    _BackupScheduleService_ActivateBackupSchedule_Handler,
		},
		{
			MethodName: "DeactivateBackupSchedule",
			Handler:    _BackupScheduleService_DeactivateBackupSchedule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ydbcp/v1alpha1/backup_schedule_service.proto",
}
