// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v6.32.1
// source: ydbcp/v1alpha1/retry.proto

package ydbcp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RetryConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// user can set number of retries or max_backoff interval.
	// if one of them is reached, retries stop.
	//
	// Types that are assignable to Retries:
	//
	//	*RetryConfig_Count
	//	*RetryConfig_MaxBackoff
	Retries isRetryConfig_Retries `protobuf_oneof:"retries"`
}

func (x *RetryConfig) Reset() {
	*x = RetryConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ydbcp_v1alpha1_retry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryConfig) ProtoMessage() {}

func (x *RetryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ydbcp_v1alpha1_retry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryConfig.ProtoReflect.Descriptor instead.
func (*RetryConfig) Descriptor() ([]byte, []int) {
	return file_ydbcp_v1alpha1_retry_proto_rawDescGZIP(), []int{0}
}

func (m *RetryConfig) GetRetries() isRetryConfig_Retries {
	if m != nil {
		return m.Retries
	}
	return nil
}

func (x *RetryConfig) GetCount() uint32 {
	if x, ok := x.GetRetries().(*RetryConfig_Count); ok {
		return x.Count
	}
	return 0
}

func (x *RetryConfig) GetMaxBackoff() *durationpb.Duration {
	if x, ok := x.GetRetries().(*RetryConfig_MaxBackoff); ok {
		return x.MaxBackoff
	}
	return nil
}

type isRetryConfig_Retries interface {
	isRetryConfig_Retries()
}

type RetryConfig_Count struct {
	Count uint32 `protobuf:"varint,1,opt,name=count,proto3,oneof"`
}

type RetryConfig_MaxBackoff struct {
	MaxBackoff *durationpb.Duration `protobuf:"bytes,2,opt,name=max_backoff,json=maxBackoff,proto3,oneof"`
}

func (*RetryConfig_Count) isRetryConfig_Retries() {}

func (*RetryConfig_MaxBackoff) isRetryConfig_Retries() {}

var File_ydbcp_v1alpha1_retry_proto protoreflect.FileDescriptor

var file_ydbcp_v1alpha1_retry_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x79, 0x64, 0x62, 0x63, 0x70, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0x2f, 0x72, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x79, 0x64,
	0x62, 0x63, 0x70, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x1a, 0x1e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6e, 0x0a, 0x0b,
	0x52, 0x65, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x16, 0x0a, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x3c, 0x0a, 0x0b, 0x6d, 0x61, 0x78, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x6f,
	0x66, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0a, 0x6d, 0x61, 0x78, 0x42, 0x61, 0x63, 0x6b, 0x6f, 0x66,
	0x66, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x73, 0x42, 0x3e, 0x5a, 0x3c,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x64, 0x62, 0x2d, 0x70,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x79, 0x64, 0x62, 0x63, 0x70, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x79, 0x64, 0x62, 0x63, 0x70, 0x2f, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x3b, 0x79, 0x64, 0x62, 0x63, 0x70, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ydbcp_v1alpha1_retry_proto_rawDescOnce sync.Once
	file_ydbcp_v1alpha1_retry_proto_rawDescData = file_ydbcp_v1alpha1_retry_proto_rawDesc
)

func file_ydbcp_v1alpha1_retry_proto_rawDescGZIP() []byte {
	file_ydbcp_v1alpha1_retry_proto_rawDescOnce.Do(func() {
		file_ydbcp_v1alpha1_retry_proto_rawDescData = protoimpl.X.CompressGZIP(file_ydbcp_v1alpha1_retry_proto_rawDescData)
	})
	return file_ydbcp_v1alpha1_retry_proto_rawDescData
}

var file_ydbcp_v1alpha1_retry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ydbcp_v1alpha1_retry_proto_goTypes = []any{
	(*RetryConfig)(nil),         // 0: ydbcp.v1alpha1.RetryConfig
	(*durationpb.Duration)(nil), // 1: google.protobuf.Duration
}
var file_ydbcp_v1alpha1_retry_proto_depIdxs = []int32{
	1, // 0: ydbcp.v1alpha1.RetryConfig.max_backoff:type_name -> google.protobuf.Duration
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ydbcp_v1alpha1_retry_proto_init() }
func file_ydbcp_v1alpha1_retry_proto_init() {
	if File_ydbcp_v1alpha1_retry_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ydbcp_v1alpha1_retry_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RetryConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_ydbcp_v1alpha1_retry_proto_msgTypes[0].OneofWrappers = []any{
		(*RetryConfig_Count)(nil),
		(*RetryConfig_MaxBackoff)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ydbcp_v1alpha1_retry_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ydbcp_v1alpha1_retry_proto_goTypes,
		DependencyIndexes: file_ydbcp_v1alpha1_retry_proto_depIdxs,
		MessageInfos:      file_ydbcp_v1alpha1_retry_proto_msgTypes,
	}.Build()
	File_ydbcp_v1alpha1_retry_proto = out.File
	file_ydbcp_v1alpha1_retry_proto_rawDesc = nil
	file_ydbcp_v1alpha1_retry_proto_goTypes = nil
	file_ydbcp_v1alpha1_retry_proto_depIdxs = nil
}
