// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.1
// source: nebius/audit/v1/common/action.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action int32

const (
	Action_ACTION_UNSPECIFIED Action = 0
	Action_ENCRYPT            Action = 24
	Action_DECRYPT            Action = 25
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0:  "ACTION_UNSPECIFIED",
		24: "ENCRYPT",
		25: "DECRYPT",
	}
	Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ENCRYPT":            24,
		"DECRYPT":            25,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_nebius_audit_v1_common_action_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_nebius_audit_v1_common_action_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_nebius_audit_v1_common_action_proto_rawDescGZIP(), []int{0}
}

var File_nebius_audit_v1_common_action_proto protoreflect.FileDescriptor

const file_nebius_audit_v1_common_action_proto_rawDesc = "" +
	"\n" +
	"#nebius/audit/v1/common/action.proto\x12\x16nebius.audit.v1.common*:\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aENCRYPT\x10\x18\x12\v\n" +
	"\aDECRYPT\x10\x19Ba\n" +
	"\x19ai.nebius.audit.v1.commonB\vActionProtoP\x01Z5ydbcp/plugins/kms_nebius/proto/nebius/audit/v1/commonb\x06proto3"

var (
	file_nebius_audit_v1_common_action_proto_rawDescOnce sync.Once
	file_nebius_audit_v1_common_action_proto_rawDescData []byte
)

func file_nebius_audit_v1_common_action_proto_rawDescGZIP() []byte {
	file_nebius_audit_v1_common_action_proto_rawDescOnce.Do(func() {
		file_nebius_audit_v1_common_action_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nebius_audit_v1_common_action_proto_rawDesc), len(file_nebius_audit_v1_common_action_proto_rawDesc)))
	})
	return file_nebius_audit_v1_common_action_proto_rawDescData
}

var file_nebius_audit_v1_common_action_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nebius_audit_v1_common_action_proto_goTypes = []any{
	(Action)(0), // 0: nebius.audit.v1.common.Action
}
var file_nebius_audit_v1_common_action_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nebius_audit_v1_common_action_proto_init() }
func file_nebius_audit_v1_common_action_proto_init() {
	if File_nebius_audit_v1_common_action_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nebius_audit_v1_common_action_proto_rawDesc), len(file_nebius_audit_v1_common_action_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nebius_audit_v1_common_action_proto_goTypes,
		DependencyIndexes: file_nebius_audit_v1_common_action_proto_depIdxs,
		EnumInfos:         file_nebius_audit_v1_common_action_proto_enumTypes,
	}.Build()
	File_nebius_audit_v1_common_action_proto = out.File
	file_nebius_audit_v1_common_action_proto_goTypes = nil
	file_nebius_audit_v1_common_action_proto_depIdxs = nil
}
